# Justin's Pyecca Point-Cloud Alignment (JPPCA)

Uses Casadi to optimize the transformation matrix T that minizies pointcloud measurement error. Uses pyecca to optimize the lie algebra se(3) elements.

# Problem Definition
Feature location definition:
$ \\ P_k = \begin{bmatrix}  x \\ y \\ z \\ 1 \end{bmatrix} \approx p_{k,0}$

Measurement of feature $k$ at pose $j$:
$ \\ p_{k,j} $

Transformation from pose $j$ to $j+1$:
$ \\ T_{j,j+1} $

Measurement error definition between poses $j$ and $j+1$ for feature $k$:
$ \\ e_{k,j+1} = p_{k,j+1} - T_{j,j+1}*p_{k,j} $

Cost function $J$:
$ \\ J(T_{j,j+1}) = \sum\limits_{k} e_{k,j+1}^T*Q*e_{k,j+1}$

So for pose $0$ to pose $1$:
$ \\ J(T_{0,1}) = \sum\limits_{k} e_{k,1}^T*Q*e_{k,1} = \sum\limits_{k} (p_{k,1} - T_{0,1}*p_{k,0})^T*Q*(p_{k,1} - T_{0,1}*p_{k,0})$

In [1]:
%load_ext autoreload
%autoreload 2
import matplotlib.pyplot as plt
%matplotlib qt
import numpy as np
import casadi as ca
import time
import BF_PCA

In [2]:
# Define symbolic variables used for optimization
trans_sym = ca.vertcat(ca.SX.sym('u'), ca.SX.sym('v'), ca.SX.sym('w'))
angles_sym = ca.vertcat(ca.SX.sym('omega1'), ca.SX.sym('omega2'), ca.SX.sym('omega3'))
all_sym = ca.vertcat(trans_sym, angles_sym)
all_sym

SX([u, v, w, omega1, omega2, omega3])

In [3]:
# Generate test data

# Points observed from pose 0:
points_0 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 0],
])

R_true = BF_PCA.euler2rot(1, 0.5, -1)
t_true = np.array([[0],
                   [0],
                   [0],
                  ])
T_01_true = np.vstack([np.hstack([R_true, t_true]), np.array([[0, 0, 0, 1]])])
T_01_true

points_1 = BF_PCA.applyT(points_0, T_01_true)

print('T_01_true:', T_01_true)
print('points_0:', points_0)
print('points_1:', points_1)

T_01_true: [[ 0.47415988 -0.67261892 -0.56811636  0.        ]
 [ 0.73846026 -0.0475419   0.67261892  0.        ]
 [-0.47942554 -0.73846026  0.47415988  0.        ]
 [ 0.          0.          0.          1.        ]]
points_0: [[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 0]]
points_1: [[ 0.47415988  0.73846026 -0.47942554]
 [-0.67261892 -0.0475419  -0.73846026]
 [-0.56811636  0.67261892  0.47415988]
 [-0.09395648  1.41107918 -0.00526566]
 [-1.24073528  0.62507702 -0.26430038]
 [-0.19845904  0.69091836 -1.2178858 ]]


In [4]:
import sys
sys.path.insert(0, '../../')
from pyecca.lie import se3, so3, matrix_lie_group
SE3 = se3._SE3()
T_sym = SE3.exp(SE3.wedge(all_sym))
T_sym

SX(@1=1, @2=((sq(omega1)+sq(omega2))+sq(omega3)), @3=sqrt(@2), @4=1e-07, @5=(fabs(@3)<@4), @6=0.5, @7=-0.0416667, @8=0.00138889, @9=((@5?((@6+(@7*@2))+(@8*sq(@2))):0)+((!@5)?((@1-cos(@3))/@2):0)), @10=(@9*omega3), @11=(@9*omega2), @12=(fabs(@3)<@4), @13=-0.166667, @14=0.00833333, @15=((@12?((@1+(@13*@2))+(@14*sq(@2))):0)+((!@12)?(sin(@3)/@3):0)), @16=(@9*omega1), @17=(@9*omega1), @18=0, @19=(@9*omega3), @20=(@9*omega2), @21=((sq(omega1)+sq(omega2))+sq(omega3)), @22=sqrt(@21), @23=(fabs(@22)<@4), @24=((@1-((@23?((@1+(@13*@21))+(@14*sq(@21))):0)+((!@23)?(sin(@22)/@22):0)))/@21), @25=(@24*omega3), @26=(@24*omega2), @27=(fabs(@22)<@4), @28=((@27?((@6+(@7*@21))+(@8*sq(@21))):0)+((!@27)?((@1-cos(@22))/@21):0)), @29=(@24*omega1), @30=(@24*omega3), @31=(@24*omega1), @32=(@24*omega2), 
[[(@1-((@10*omega3)+(@11*omega2))), ((@11*omega1)-(@15*omega3)), ((@15*omega2)+(@10*omega1)), ((((@1-((@25*omega3)+(@26*omega2)))*u)+(((@26*omega1)-(@28*omega3))*v))+(((@28*omega2)+(@25*omega1))*w))], 
 [((@15*om

In [5]:
# Build casadi cost function
J = BF_PCA.build_cost_pyecca(
            points_0=points_0,
            points_1=points_1,
            all_sym=all_sym)

# Setup and run optimizer
# Symbols/expressions
nlp = {}                 # NLP declaration
nlp['x'] = all_sym       # decision vars
nlp['f'] = J      # objective
nlp['g'] = 0             # constraints

# Create solver instance
# opts = {'ipopt.print_level':0, 'print_time':0, 'ipopt.sb': 'yes'}
# F = ca.nlpsol('F','ipopt',nlp,opts);
F = ca.nlpsol('F','ipopt',nlp);

# Solve the problem using a guess
# This uses original landmark/measure association (associates which landmark we think the measurement is measuring)
x_input = np.array([1, 1, 1, 1, 1, 1])
optim = F(x0=x_input)


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.3, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:       21

Total number of variables............................:        6
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equa

In [10]:
SE3 = se3._SE3()
T_01_hat = SE3.exp(SE3.wedge(np.array(optim['x'])))

# points_1 = BF_PCA.applyT(points_0, T_01_hat)
# points_1

In [11]:
T_01_true

array([[ 0.47415988, -0.67261892, -0.56811636,  0.        ],
       [ 0.73846026, -0.0475419 ,  0.67261892,  0.        ],
       [-0.47942554, -0.73846026,  0.47415988,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [12]:
T_01_hat

SX(@1=0, 
[[0.47416, -0.672619, -0.568116, -1.52455e-10], 
 [0.73846, -0.0475419, 0.672619, -1.3717e-10], 
 [-0.479426, -0.73846, 0.47416, -9.63762e-11], 
 [@1, @1, @1, 1]])

In [13]:
float(optim['f'])

1.1717215472454526e-19